export let hotelCityData = {
  "hotels-in-agra": ["4-star", "3-star", "2-star"],
  "hotels-in-ajmer": [],
  "hotels-in-alappuzha": [],
  "hotels-in-almora": [],
  "hotels-in-alwar": [],
  "hotels-in-ammathi": [],
  "hotels-in-amritsar": ["under-1000", "4-star", "3-star", "2-star"],
  "hotels-in-anchal": [],
  "hotels-in-ayodhya": [],
  "hotels-in-bhuj": [],
  "hotels-in-bikaner": ["3-star"],
  "hotels-in-bir-billing": [],
  "hotels-in-chail": [],
  "hotels-in-chandigarh": ["4-star", "3-star"],
  "hotels-in-chaugan": [],
  "hotels-in-dehradun": ["3-star"],
  "hotels-in-dhanolti": [],
  "hotels-in-dharamshala": ["3-star"],
  "hotels-in-dwarka": [],
  "hotels-in-ernakulam": [],
  "hotels-in-gautam-budh-nagar(noida)": ["4-star", "3-star"],
  "hotels-in-ghaziabad": [],
  "hotels-in-goa": ["3-star"],
  "hotels-in-gulmarg": ["4-star"],
  "hotels-in-gurugram": [],
  "hotels-in-haridwar": ["under-500"],
  "hotels-in-howrah": [],

  "hotels-in-idukki": [],
  "hotels-in-jaipur": [
    "under-500",
    "under-1500",
    "under-2000",
    "under-1000",
    "under-3000",
    "under-5000",
    "4-star",
    "3-star",
    "2-star",
  ],
  "hotels-in-jaisalmer": ["3-star"],
  "hotels-in-jammu": [],
  "hotels-in-jamnagar": [],
  "hotels-in-jhansi": [],
  "hotels-in-jim-corbett": ["4-star", "3-star"],
  "hotels-in-jodhpur": ["4-star", "3-star", "2-star"],
  "hotels-in-junagadh": [],
  "hotels-in-kanpur-nagar": ["3-star"],
  "hotels-in-kasauli": ["4-star", "3-star"],
  "hotels-in-kasauni": [],
  "hotels-in-kodagu": [],
  "hotels-in-kolkata": [
    "3-star",
  ],
  "hotels-in-lansdowne": ["3-star"],
  "hotels-in-leh": [],
  "hotels-in-lohaghat": [],
  "hotels-in-lucknow": ["3-star"],
  "hotels-in-ludhiana": [],
  "hotels-in-manali": ["under-1000","4-star", "3-star"],
  "hotels-in-mathura": ["under-1000"],
  "hotels-in-mcleodganj": [],
  "hotels-in-mount-abu": [
    "under-2000",
    "4-star",
    "3-star",
  ],
  "hotels-in-mukteshwar": [],
  "hotels-in-mumbai-city": [
  ],
  "hotels-in-mussoorie": [
    "under-1500",
    "4-star",
    "3-star",
    "2-star",
  ],
  "hotels-in-mysore": ["4-star", "3-star"],
  "hotels-in-nainital": [
    "under-2000",
    "4-star",
    "3-star",
  ],
  "hotels-in-narkanda": [],
  "hotels-in-new-delhi": [
    "under-500",
    "under-1000",
    "under-2000",
    "under-3000",
    "under-5000",
    "under-1500",
    "4-star",
    "3-star",
    "2-star",
  ],
  "hotels-in-pahalgam": ["3-star"],
  "hotels-in-patna": ["3-star"],
  "hotels-in-porbandar": [],
  "hotels-in-puri": ["3-star"],
  "hotels-in-pushkar": [],
  "hotels-in-raipur": [
    "3-star",
  ],
  "hotels-in-rajkot": ["3-star"],
  "hotels-in-ranikhet": [],
  "hotels-in-ranthambore": [],
  "hotels-in-rishikesh": ["4-star", "3-star"],
  "hotels-in-rudraprayag": [],
  "hotels-in-sawai-madhopur": [],
  "hotels-in-shimla": [
    "under-500",
    "under-1000",
    "under-1500",
    "4-star",
    "3-star",
  ],
  "hotels-in-srinagar-district": ["4-star", "3-star"],
  "hotels-in-surat": ["3-star"],
  "hotels-in-the-nilgiris": [],
  "hotels-in-udaipur": [
    "under-1000",
    "under-2000",
    "under-1500",
    "under-3000",
    "under-5000",
    "under-3000",
    "4-star",
    "3-star",
  ],
  "hotels-in-ujjain": ["3-star"],
  "hotels-in-varanasi": ["under-1000","3-star"],
  "hotels-in-vrindavan": ["3-star"],
  "hotels-in-zirakpur": [],
};

export const hotelregionData = {
  "hotels-in-agra": {
    "civil-line": [],
    "fatehabad-road": [],
    lohamandi: [],
    "raja-ki-mandi": [],
    "sadar-bazaar-": [],
    "sanjay-place": [],
    "taj-ganj": [],
  },
  "hotels-in-ajmer": { "ajmer-sharif": [] },
  "hotels-in-alappuzha": {},
  "hotels-in-almora": { binsar: [] },
  "hotels-in-alwar": {
    "alwar-junction-railway-station": [],
    bakhera: [],
    naharpur: [],
  },
  "hotels-in-ammathi": {},
  "hotels-in-amritsar": {
    "golden-temple": [],
    gumtala: [],
    "jallianwala-bagh-": [],
    katra: [],
    "mall-of-amritsar": [],
    "shastri-nagar": [],
  },
  "hotels-in-anchal": {},
  "hotels-in-ayodhya": {},
  "hotels-in-bikaner": { bikaner: [] },
  "hotels-in-bir-billing": { bir: [], jogindarnagar: [], "solang-valley": [] },
  "hotels-in-chail": {
    "-kandaghat": [],
    "chail-palace": [],
    mahog: [],
    nihara: [],
  },
  "hotels-in-chandigarh": {
    "chandigarh-international-airport": [],
    "elante-mall": [],
    manimajra: [],
    nayagaon: [],
    panchkula: [],
    "rock-garden": [],
    "sector-17": [],
    "sector-42": [],
    "sector-8": [],
    "sukhna-lake": [],
  },
  "hotels-in-chaugan": {},
  "hotels-in-dehradun": {
    chukkuwala: [],
    "paltan-bazaar": [],
    "rajender-nagar": [],
  },
  "hotels-in-dhanolti": {},
  "hotels-in-dharamshala": {
    "bhagsu-nag": [],
    "dharamsala-bus-station": [],
    kand: [],
    loharkar: [],
    "mcleod-ganj": [],
  },
  "hotels-in-dwarka": {},
  "hotels-in-ernakulam": { kochi: [] },
  "hotels-in-gautam-budh-nagar(noida)": {
    "greater-noida": [],
    "knowledge-park-iii": [],
    noida: [],
    "sector-66": [],
  },
  "hotels-in-ghaziabad": {
    faridabad: [],
    gurugram: [],
    indirapuram: [],
    kaushambi: [],
    "new-delhi": [],
    "noida-": [],
  },
  "hotels-in-goa": {
    "anjuna-beach": [],
    "baga-beach": [],
    calangute: [],
    "candolim-": [],
    morjim: [],
    "old-goa": [],
    "palolem-beach": [],
    panaji: [],
  },
  "hotels-in-gulmarg": {},
  "hotels-in-gurugram": {
    "city-center-sector-29": [],
    "dlf-cyber-city": [],
    "dlf-phase-i": [],
    "dlf-phase-ii": [],
    "dlf-phase-iii": [],
    "old-gurgaon": [],
    "sector-14": [],
    "sector-24": [],
    "sector-25": [],
    "sector-31": [],
  },
  "hotels-in-haridwar": {
    "birla-ghat": [],
    devpura: [],
    "har-ki-pauri": [],
    "khanna-nagar-": [],
    "mansa-devi-temple": [],
    mayapur: [],
    "pentagon-mall": [],
    "sharvan-nath-nagar": [],
  },
  "hotels-in-howrah": {},
  "hotels-in-idukki": {
    "kundala-dam-lake-munnar": [],
    "lockheart-gap": [],
    munnar: [],
  },
  "hotels-in-jaipur": {
    bhakrota: [],
    brahampuri: [],
    "c-scheme": [],
    gopalbari: [],
    jagatpura: [],
    "jaipur-airport": [],
    "jal-mahal": [],
    "jawahar-circle": [],
    "jhotwara-": [],
    kanakpura: [],
  },
  "hotels-in-jaisalmer": {
    "jaisalmer-fort": [],
    "kishan-ghat": [],
    "lake-gadisar": [],
    "patwon-ki-haveli": [],
  },
  "hotels-in-jammu": {
    "bari-brahmana": [],
    "jammu-and-kashmir": [],
    "prem-nagar": [],
  },
  "hotels-in-jamnagar": {},
  "hotels-in-jhansi": {},
  "hotels-in-jim-corbett": { "-nagina": [], khempur: [], ramnagar: [] },
  "hotels-in-jodhpur": {
    "clock-tower": [],
    "gulab-sagar": [],
    "jodhpur-airport": [],
    paota: [],
    ratanada: [],
    sardarpura: [],
    "shashtri-nagar": [],
  },
  "hotels-in-junagadh": {},
  "hotels-in-kanpur-nagar": { barra: [], "sharda-nagar": [] },
  "hotels-in-kasauli": { garkhal: [], nahan: [] },
  "hotels-in-kasauni": { bajinath: [], kasauni: [], "kausani-retreat": [] },
  "hotels-in-kodagu": {},
  "hotels-in-kolkata": { "bbd-bagh": [] },
  "hotels-in-lansdowne": { dugadda: [] },
  "hotels-in-leh": { gangles: [], "nubra-valley": [] },
  "hotels-in-lohaghat": {},
  "hotels-in-lucknow": {
    "-gomti-nagar": [],
    alambagh: [],
    aminabad: [],
    budheshwar: [],
    lalbagh: [],
    "lucknow-international-airport": [],
    "lucknow-railway-station": [],
  },
  "hotels-in-ludhiana": { "dhandari-kalan": [], ludhiana: [], ramgarh: [] },
  "hotels-in-manali": {
    aleo: [],
    "city-centre": [],
    kufri: [],
    "mall-road": [],
    manali: [],
    prini: [],
    rangri: [],
    sethan: [],
    "solang-valley": [],
  },
  "hotels-in-mathura": {
    "bankey-bihari-temple": [],
    "iskcon-vrindavan": [],
    "jagannath-puri": [],
    "mathura-train-station": [],
    "mayur-vihar": [],
    "prem-mandir": [],
    "sri-krishna-janmabhoomi": [],
  },
  "hotels-in-mcleodganj": { "masroor-temples": [], mcleodganj: [] },
  "hotels-in-mount-abu": { dhundayi: [], "nakki-lake": [], "sani-gaon": [] },
  "hotels-in-mukteshwar": { mukteshwar: [], uttarakhand: [] },
  "hotels-in-mumbai-city": { mumbai: [] },
  "hotels-in-mussoorie": {
    "kempty-falls": [],
    landour: [],
    "mussoorie-lake": [],
    "the-mall-road": [],
  },
  "hotels-in-mysore": { doora: [], mysore: [], "tilak-nagar": [] },
  "hotels-in-nainital": {
    mallital: [],
    "nainital-lake": [],
    sherwani: [],
    tallital: [],
    "tiffin-top": [],
  },
  "hotels-in-new-delhi": {
    barakhamba: [],
    chanakyapuri: [],
    "chandani-chowk": [],
    "connaught-palace": [],
    daryaganj: [],
    "east-of-kailash": [],
    "greater-kailash-i": [],
    "green-park": [],
    "kamla-nagar": [],
    "karol-bagh": [],
    paharganj: [
      "under-1000",
      "under-2000",
      "under-3000",
      "under-4000",
      "under-5000",
      "2-star",
      "3-star",
      "4-star",
      "5-star",
    ],
  },
  "hotels-in-ooty": {},
  "hotels-in-pahalgam": {},
  "hotels-in-patna": { "gandhi-maidan": [] },
  "hotels-in-porbandar": {},
  "hotels-in-puri": { puri: [] },
  "hotels-in-pushkar": {
    ganahera: [],
    "merta-city": [],
    "pushkar-lake": [],
    "rangji-temple": [],
  },
  "hotels-in-raipur": { "jawahar-nagar": [], pandri: [], raipur: [] },
  "hotels-in-rajkot": {},
  "hotels-in-ranikhet": { "the-mall-road": [] },
  "hotels-in-ranthambore": { "sawai-madhopur": [] },
  "hotels-in-rishikesh": {
    "laxman-jhula": [],
    "parmarth-niketan-ashram": [],
    "ram-jhula": [],
    "rishikesh-railway-station": [],
    tapovan: [],
    "triveni-ghat": [],
  },
  "hotels-in-rudraprayag": {},
  "hotels-in-sawai-madhopur": {},
  "hotels-in-shimla": {
    beolia: [],
    dudhli: [],
    "kachi-ghatti": [],
    kaithu: [],
    kanholi: [],
    kanlog: [],
    kufri: [],
    "the-mall-road": [],
    totu: [],
  },
  "hotels-in-srinagar-district": {
    chattabal: [],
    "chinar-bagh": [],
    "dal-lake": [],
    "lal-chowk": [],
    "nishat-shalimar": [],
    rajbagh: [],
  },
  "hotels-in-surat": {},
  "hotels-in-udaipur": {
    bhuwana: [],
    "lake-pichola": [],
    "nada-khada": [],
    panchwati: [],
    "pratap-nagar": [],
    shilpgram: [],
    "subhas-nagar": [],
  },
  "hotels-in-ujjain": { ujjain: [] },
  "hotels-in-varanasi": { chetganj: [], manduwa: [], vanarasi: [] },
  "hotels-in-vrindavan": { "rukmani-vihar": [] },
  "hotels-in-zirakpur": { chandigarh: [], zirakpur: [] },
};
