import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:3000/');
  await page.getByRole('link', { name: 'Hotels' }).click();
  await page.getByRole('link', { name: 'eVisa' }).click();
  await page.getByRole('link', { name: 'Home', exact: true }).click();
  await page.getByTitle('contactUs', { exact: true }).click();
  await page.goto('http://localhost:3000/');
  await page.getByTitle('aboutUs', { exact: true }).click();
  await page.goto('http://localhost:3000/');
  await page.getByRole('link', { name: 'delhi_image New Delhi Where' }).click();
  await page.getByText('Pet Allowed').click();
  await page.getByRole('button', { name: 'Clear Filters' }).click();
  await page.locator('div:nth-child(48) > .mt-4 > div > svg:nth-child(2)').click();
  const page1Promise = page.waitForEvent('popup');
  await page.getByText('Staybook Hotel AiraPaharganj, New Delhi4.6 / 5587 Ratings').click();
  const page1 = await page1Promise;
  await page1.goto('http://localhost:3000/hotels/staybook-aira-xing-new-delhi');
  await page1.getByRole('link', { name: 'Hotel Info', exact: true }).click();
  await page1.getByRole('link', { name: 'Room Plans' }).click();
  await page1.getByRole('link', { name: 'Reviews' }).click();
  await page1.getByRole('link', { name: 'Amenities' }).click();
  await page1.getByRole('link', { name: 'Nearby Places' }).click();
  await page1.getByRole('link', { name: 'FAQs' }).click();
  await page1.getByRole('link', { name: 'Hotel Policies' }).click();
  await page1.getByRole('link', { name: 'Nearby Places' }).click();
  await page1.getByRole('link', { name: 'Amenities' }).click();
  await page1.getByRole('button', { name: 'Show All Amenities' }).click();
  await page1.getByRole('button', { name: 'close model' }).click();
  await page1.getByRole('button', { name: 'Show all Nearby Places' }).click();
  await page1.getByRole('button', { name: 'close model' }).click();
  await page1.getByRole('button', { name: 'Show all Faqs' }).click();
  await page1.getByRole('button', { name: 'close model' }).click();
  await page1.getByRole('link', { name: 'Hotel Policies' }).click();
  const page2Promise = page1.waitForEvent('popup');
  await page1.getByRole('link', { name: 'hotel info img Staybook Atlanta New Delhi Train Station New Delhi View Hotel' }).getByRole('button').click();
  const page2 = await page2Promise;
  await page2.getByPlaceholder('Checkin Date').click();
  await page2.getByRole('button', { name: 'Next month' }).click();
  await page2.getByRole('button', { name: 'Next month' }).click();
  await page2.getByRole('button', { name: '17' }).first().click();
  await page2.getByRole('button', { name: '20' }).first().click();
  await page2.locator('div').filter({ hasText: /^2$/ }).getByRole('button').first().click();
  await page2.getByRole('button', { name: 'Proceed' }).click();
  await page2.goto('http://localhost:3000/hotels/staybook-atlanta-new-delhi-train-station-new-delhi/rooms?checkin=17-11-2024&checkout=20-11-2024&num_nights=3&num_guests=1&num_adults=1&num_rooms=1&num_children=0');
  await page2.getByRole('button', { name: 'Show More' }).click();
  await page2.getByText('Close', { exact: true }).click();
  await page2.getByRole('link', { name: 'Room Plans' }).click();
  await page2.getByRole('link', { name: 'Reviews' }).click();
  await page2.getByRole('link', { name: 'Amenities' }).click();
  await page2.getByRole('link', { name: 'Location' }).click();
  await page2.getByRole('link', { name: 'Nearby Places' }).click();
  await page2.getByRole('link', { name: 'Hotel Info' }).click();
  await page2.getByRole('link', { name: 'FAQs' }).click();
  await page2.getByRole('link', { name: 'Hotel Policies' }).click();
  await page2.getByRole('button', { name: 'See More +' }).click();
  await page2.getByRole('button', { name: 'See Less -' }).click();
  await page2.getByRole('button', { name: 'Show all Policies' }).click();
  await page2.getByRole('button', { name: 'close model' }).click();
  await page2.getByRole('button', { name: 'Show all Faqs' }).click();
  await page2.getByRole('button', { name: 'close model' }).click();
  await page2.getByRole('button', { name: 'Show all Nearby Places' }).click();
  await page2.getByRole('button', { name: 'close model' }).click();
  await page2.getByRole('button', { name: 'Show all Reviews' }).click();
  await page2.getByRole('button', { name: 'close model' }).click();
  await page2.getByRole('button', { name: 'Book Now' }).click();
  await page2.getByRole('button').first().click();
  await page2.getByRole('button', { name: 'view price brakeup' }).click();
  await page2.getByPlaceholder('Enter your first name').click();
  await page2.getByPlaceholder('Enter your first name').fill('Rishabh');
  await page2.getByPlaceholder('Enter your first name').press('Tab');
  await page2.getByPlaceholder('Enter your last name').fill('Testing_Playwright_Buttons');
  await page2.getByPlaceholder('Enter your last name').press('Tab');
  await page2.getByPlaceholder('Enter your email').fill('hespnod45@gmail.com');
  await page2.getByPlaceholder('Enter your email').press('Tab');
  await page2.getByPlaceholder('1 (702) 123-').fill('+91 92050-97674');
  await page2.getByRole('button', { name: 'Proceed To Payment Options' }).click();
  await page2.getByText('Pay at Hotel₹').click();
  await page2.getByRole('button', { name: 'Proceed to pay at Hotel' }).click();
});