export const countriesData = [
  {
    label: "Albanian",
    link: "albanian",
    flag: "🇦🇱",
    key: 0,
    value: "Albania",
    code: "AL",
    address: {
      country: "Honorary Consulate of Albania in New Delhi, India",
      address: "Sara House, A‐31, Hauz Khas, New Delhi 110016, India",
      city: "New Delhi",
      phone: "26517134, 26517741",
      fax: "26517127",
      email: "dpsingh@sara‐intl.com",
    },
  },
  {
    label: "Andorran",
    link: "andorran",
    flag: "🇦🇩",
    key: 1,
    value: "Andorra",
    code: "AD",
    address: [],
  },
  {
    label: "Angolan",
    link: "angolan",
    flag: "🇦🇴",
    key: 2,
    value: "Angola",
    code: "AO",
    address: {
      country: "Angolan Embassy in New Delhi, India",
      address: "5, Poorvi Marg, Vasant Vihar, New Delhi 110057, India",
      city: "New Delhi",
      phone: "26146197, 26146195",
      fax: "26146190, 26146184",
      email: "xietuang@del2.vsnl.net.in",
    },
  },
  {
    label: "Anguillan",
    link: "anguillan",
    flag: "🇦🇮",
    key: 3,
    value: "Anguilla",
    code: "AI",
    address: {
      country: "Honorary Consulate of Albania in New Delhi, India",
      address: "Shantipath, Chanakyapuri South West Delhi 110021 Delhi India",
      city: "New Delhi",
      phone: "+91 11 2419 2100",
      fax: "26517+91 (11) 2419 2492127",
      email: "web.newdelhi@fco.gov.uk",
    },
  },
  {
    label: "Argentinian",
    link: "argentinian",
    flag: "🇦🇷",
    key: 5,
    value: "Argentina",
    code: "AR",
    address: {
      country: "Argentinian Embassy in New Delhi, India",
      address: "A‐2/6, Vasant Vihar, New Delhi 110057, India",
      city: "New Delhi",
      phone: "41661982/83/84, 41661987",
      fax: "(+91) 11 4166-1988-89",
      email: "embargentindi@yahoo.com",
    },
  },
  {
    label: "Armenian",
    link: "armenian",
    flag: "🇦🇲",
    key: 6,
    value: "Armenia",
    code: "AM",
    address: {
      country: "Armenian Embassy in New Delhi, India",
      address: "Armenia Street D-133, Anand Niketan, New Delhi-110021, India",
      city: "New Delhi",
      phone: "(9111) 24112851 / 52",
      fax: "(9111) 24112853",
      email: "armindiaembassy@mfa.am",
    },
  },
  {
    label: "Aruban",
    link: "aruban",
    flag: "🇦🇼",
    key: 7,
    value: "Aruba",
    code: "AW",
    address: {
      address:
        "1st floor, Forbes Building, Charanjit Rai Marg, Azad Maidan, Fort. Mumbai 400001.",
      phone: "+91 22 2219 4200",
      city: "Mumbai",
      fax: "912222194230",
      email: "bom@minbuza.nl.",
    },
  },
  {
    label: "Australian",
    link: "australian",
    flag: "🇦🇺",
    key: 8,
    value: "Australia",
    code: "AU",
    address: {
      country: "Australian Consulate in New Delhi, India",
      address: "1/50 G, Shantipath, Chanakyapuri, New Delhi 110021",
      city: "New Delhi",
      phone: "+91 11 4139 9900",
      fax: "+91 11 2687 2228",
      email: "",
    },
  },
  {
    label: "Austrian",
    link: "austrian",
    flag: "🇦🇹",
    key: 9,
    value: "Austria",
    code: "AT",
    address: {
      country: "Austrian Embassy in New Delhi, India",
      address:
        "EP-13, Chandragupta Marg, Chanakyapuri, New Delhi, Delhi 110021",
      city: "New Delhi",
      phone: "(+91) (11) 24 19 27 00",
      fax: "(+91) (11) 26 88 69 29",
      email: "new-delhi-kf@bmeia.gv.at",
    },
  },
  {
    label: "Azerbaijani",
    link: "azerbaijani",
    flag: "🇦🇿",
    key: 10,
    value: "Azerbaijan",
    code: "AZ",
    address: {
      country: "Azerbaijani Embassy in New Delhi, India",
      address:
        "41, Paschimi Marg, Block-D, Opp Vasanth Vihar Club, Vasant Vihar, D41, Block D, Vasant Vihar, New Delhi, Delhi 110057",
      city: "New Delhi",
      phone: "+91 (11) 26 15 22 28",
      fax: "+91 (11) 26 15 22 27",
      email: "",
    },
  },
  {
    label: "Bahamian",
    link: "bahamian",
    flag: "🇧🇸",
    key: 11,
    value: "Bahamas",
    code: "BS",
    address: {
      address: "Shantipath Chanakyapuri South West Delhi 110021 Delhi India",
      city: "New Delhi",
      phone: "",
      fax: "+91 (11) 2419 2492 , +91 (11) 2419 2400 +91 (11) 2419 2301",
      email: "",
    },
  },
  {
    label: "Bangladeshi",
    link: "bangladeshi",
    flag: "🇧🇩",
    key: 12,
    value: "Bangladesh",
    code: "BD",
    address: {
      country: "Bangladeshi Embassy in New Delhi, India",
      address:
        "EP-39, Dr. S. RadhaKrishnan Marg Chanakyapuri, New Delhi-110021",
      city: "New Delhi",
      phone: "683 4668 and/or 683 4065",
      fax: "684 0596",
      email: "mission.newdelhi@mofa.gov.bd",
    },
  },
  {
    label: "Barbadian",
    link: "barbadian",
    flag: "🇧🇧",
    key: 13,
    value: "Barbados",
    code: "BB",
    address: {
      address: "Shantipath, Chanakyapuri South West Delhi 110021 Delhi India",
      phone: "",
      fax: "+91 (11) 2419 2492 , +91 (11) 2419 2400 +91 (11) 2419 2301",
      city: "New Delhi",
      email: "",
    },
  },
  {
    label: "Belarusian",
    link: "belarusian",
    flag: "🇧🇾",
    key: 14,
    value: "Belarus",
    code: "BY",
    address: {
      country: "Belarusian Embassy in New Delhi, India",
      address: "F6/8B,, Vasant Vihar, New Delhi, Delhi 110057",
      city: "New Delhi",
      phone: "(+91) 11-2469 4518",
      fax: "(+91) 11-2469 7029",
      email: "india@mfa.gov.by",
    },
  },
  {
    label: "Belgian",
    link: "belgian",
    flag: "🇧🇪",
    key: 15,
    value: "Belgium",
    code: "BE",
    address: {
      country: "Belgian Consulate in New Delhi, India",
      address: "50-N, Shantipath, Chanakyapuri, New Delhi, Delhi 110021",
      city: "New Delhi",
      phone: "+ (91) (11) 42.42.80.00",
      fax: "+ (91) (11) 42.42.80.02",
      email: "newdelhi@diplobel.fed.be",
    },
  },
  {
    label: "Belizean",
    link: "belizean",
    flag: "🇧🇿",
    key: 16,
    value: "Belize",
    code: "BZ",
    address: {
      country: "Belizean Consulate in New Dehli, India",
      address: "G7X2+2X8, Nehru Place, New Delhi, Delhi 110048",
      city: "New Dehli",
      phone: "+91 11 26421245",
      fax: "+91 11 26427125",
      email: "belize@modigroup.com",
    },
  },
  {
    label: "Beninese",
    link: "beninese",
    flag: "🇧🇯",
    key: 17,
    value: "Benin",
    code: "BJ",
    address: {
      address:
        "N-14, Pancheel Park Sector - 6 R.K. Puram Market New Delhi - 110017 India",
      city: "New Delhi",
      phone: "+229 21-385 220, 97-974 502, 95-954 091, 90-905 105",
      email: "ambabenindelhi@yahoo.fr",
      fax: "",
    },
  },
  {
    label: "Bolivian",
    link: "bolivian",
    flag: "🇧🇴",
    key: 18,
    value: "Bolivia",
    code: "BO",
    address: {
      address: "E-14/15, First Floor Vasant Vihar New Delhi - 110057",
      city: "New Delhi",
      phone: "+91-11-4606 0934",
      fax: "\t+91-11-4606 0935",
      email: "embassy.bolivia.in@gmail.com",
    },
  },
  {
    label: "Bosnian",
    link: "bosnian",
    flag: "🇧🇦",
    key: 19,
    value: "Bosnia & Herzegovina",
    code: "BA",
    address: {
      address: "E-8/5, Vasant Vihar, New Delhi, Delhi (NCT) - 110057",
      city: "New Delhi",
      phone: "+91-11-41662481, +91-11-26147415",
      fax: "+91-11-41662482",
      email: "abhind@gmail.com",
    },
  },
  {
    label: "Botswanan",
    link: "botswanan",
    flag: "🇧🇼",
    key: 20,
    value: "Botswana",
    code: "BW",
    address: {
      address: "F8/3, Vasant Vihar New Delhi - 110057 India",
      city: "New Dehli",
      phone: "(91) 11 46537000",
      fax: "(91) 11 46036191",
      email: "botind@gov.bw",
    },
  },
  {
    label: "Brazilian",
    link: "brazilian",
    flag: "🇧🇷",
    key: 21,
    value: "Brazil",
    code: "BR",
    address: {
      address: "8, Dr APJ Abdul Kalam Rd, Aurangzeb Road, New Delhi 110011",
      city: "New Dehli",
      phone: "+ (9111) 301 7301",
      fax: "+ (9111) 379 3684",
      email: "consular.newdelhi@itamaraty.gov.br",
    },
  },
  {
    label: "Bruneian",
    link: "bruneian",
    flag: "🇧🇳",
    key: 22,
    value: "Brunei",
    code: "BN",
    address: {
      address: " E-11/9 Vasant Vihar, New Delhi, Delhi (NCT) - 110057",
      city: "New Dehli",
      phone: "(+91) (11) 2614 8340/3",
      fax: "(+91) (11) 2614 2101/ 91(11) 2615 2507",
      email: "newdelhi.india@mfa.gov.bn",
    },
  },
  {
    label: "Bulgarian",
    link: "bulgarian",
    flag: "🇧🇬",
    key: 23,
    value: "Bulgaria",
    code: "BG",
    address: {
      address: "16/17 Chandragupta Marg, Chanakyapuri, New Delhi – 110021",
      city: "New Dehli",
      phone: "00911126115549",
      fax: "00911126876190",
      email: "embassy.delhi@mfa.bg",
    },
  },
  {
    label: "Burundian",
    link: "burundian",
    flag: "🇧🇮",
    key: 25,
    value: "Burundi",
    code: "BI",
    address: {
      address: "E - 9/18 Vasant Vihar New Delhi - 110057",
      phone: "+91-11-46151947 (O)",
      fax: "+91-11-49503170",
      email: "ambabudelhiyahoo.fr",
      city: "New Delhi",
    },
  },
  {
    label: "Cambodian",
    link: "cambodian",
    flag: "🇰🇭",
    key: 27,
    value: "Cambodia",
    code: "KH",
    address: {
      address: "W-112, Greater Kailash Part-II, New Delhi 110048",
      city: "New Delhi",
      phone: "(91-11) 2921 4436",
      fax: "(91-11) 2921 4438",
      email: "cambodianembassykapoor@yahoo.com",
    },
  },
  {
    label: "Canadian",
    link: "canadian",
    flag: "🇨🇦",
    key: 29,
    value: "Canada",
    code: "CA",
    address: {
      address: " 7/8, Shantipath, Chanakyapuri",
      city: "New Delhi",
      phone: "+91-11-4178 2000/ 2100",
      fax: "+91-11-4178 2020",
      email: "delhi@international.gc.ca",
    },
  },
  {
    label: "Chilean",
    link: "chilean",
    flag: "🇨🇱",
    key: 32,
    value: "Chile",
    code: "CL",
    address: {
      country: "Chilean Embassy in New Delhi, India",
      address: "A-16/1 Poorvi Marg, Vasant Vihar, New Delhi 110057",
      city: "New Delhi",
      phone: "+91 11 431 00400",
      fax: "+91 11 431 00431",
      email: "embassy@chileindia.com",
    },
  },
  {
    label: "Colombian",
    link: "colombian",
    flag: "🇨🇴",
    key: 34,
    value: "Colombia",
    code: "CO",
    address: {
      address: "F-2/2 Ground Floor, Vasant Vihar, South West Delhi 110057",
      city: "New Delhi",
      phone: "91 11 41662109/06/05",
      fax: "91 11 41662104/08",
      email: "eindia@chancery.gov.co",
    },
  },
  {
    label: "Comoran",
    link: "comoran",
    flag: "🇰🇲",
    key: 35,
    value: "Comoros",
    code: "KM",
    address: {
      email: "klganju_comoros@hotmail.com",
      address: "27-28, D.S., Ground Floor New Rajinder Nagar, New Delhi 110060",
      phone: "+91 11 2874 1319/28",
      fax: "91-11-2874 1326, 2582 3110",
      city: "New Delhi",
    },
  },
  {
    label: "Costa Rican",
    link: "costa-rican",
    flag: "🇨🇷",
    key: 37,
    value: "Costa Rica",
    code: "CR",
    address: {
      country: "Costa Rican Consulate in New Delhi, India",
      address: "2/15, Third Floor, Shanti Niketan",
      city: "New Delhi",
      phone: "00 (911) 1-233 1 0212/ 00 (911) 1-233 1 4934",
      fax: "00 (911) 1-23327231/00 (911) 1- 23357473",
      email: "embajadacostarica.india@gmail.com",
    },
  },
  {
    label: "Croatian",
    link: "croatian",
    flag: "🇭🇷",
    key: 38,
    value: "Croatia",
    code: "HR",
    address: {
      address: "A-15 West End, New Delhi 110021, India",
      city: "New Delhi",
      phone: "0091 11 4166 3101",
      fax: "0091 11 2411 6873, 4166 3100",
      email: "croemb.new-delhi@mvpei.hr",
    },
  },
  {
    label: "Cuban",
    link: "cuban",
    flag: "🇨🇺",
    key: 39,
    value: "Cuba",
    code: "CU",
    address: {
      country: "Cuban Embassy in New Delhi, India",
      address: "C-102, Block C, South Extension Part 2, New Delhi 110049",
      city: "New Delhi",
      phone: "(91-11) 292 2467, 2924 2468, 2923, 2470",
      fax: "(91-11) 2923 2469",
      email: "embcuind@del6.vsnl.net.in",
    },
  },
  {
    label: "Cypriot",
    link: "cypriot",
    flag: "🇨🇾",
    key: 40,
    value: "Cyprus",
    code: "CY",
    address: {
      country: "Cypriot Consulate in Mumbai, India",
      address: "Honorary Consulate of the Republic of Cyprus in Mumbai, India",
      city: "Mumbai",
      phone: "(009122) 24900346, 24900650",
      fax: "(009122) 24926464, 24900314",
      email: "rana.kapoor@yesbankltd.com",
    },
  },
  {
    label: "Czech",
    link: "czech",
    flag: "🇨🇿",
    key: 41,
    value: "Czech Republic",
    code: "CZ",
    address: {
      country: "Czech Embassy in New Delhi, India",
      address: "50-M, Niti Marg Chanakyapuri 110021 New Delhi India",
      city: "New Delhi",
      phone: "+91-11-26110205",
      fax: "+91-11-26886221",
      email: "newdelhi@embassy.mzv.cz",
    },
  },
  {
    label: "Danish",
    link: "danish",
    flag: "🇩🇰",
    key: 42,
    value: "Denmark",
    code: "DK",
    address: {
      country: "Danish Embassy in New Delhi, India",
      address:
        "33-B, Dr. S. Radhakrishnan Marg, Chanakyapuri, New Delhi - 110021",
      city: "New Delhi",
      phone: "+91 11 4209 0700",
      fax: "+91 11 379 2019/+91 11 2379 2891",
      email: "delamb@um.dk",
    },
  },
  {
    label: "Djiboutian",
    link: "djiboutian",
    flag: "🇩🇯",
    key: 43,
    value: "Djibouti",
    code: "DJ",
    address: {
      email: "embassyofdjibouti@touchtelindia.net",
      addresss:
        "C/2/8, Street C2, Block C, Vasant Vihar, South West Delhi 110057",
      city: "New Delhi",
      phone: "+91 11 4135 4493, +91 11 4135 4492",
      fax: "",
    },
  },
  {
    label: "Dominican",
    link: "dominican",
    flag: "🇩🇲",
    key: 44,
    value: "Dominica",
    code: "DM",
    address: {
      email: "dominica_shukla@vsnl.net",
      address: " 283, Gulmohar Enclave, New Delhi 110049",
      city: "New Delhi",
      phone: "+91 11 2686 2595",
      fax: "+91-11-26510860",
    },
  },
  {
    label: "Dominican",
    link: "dominican",
    flag: "🇩🇴",
    key: 45,
    value: "Dominican Republic",
    code: "DO",
    address: {
      email: "contact@dominicanembassy.in",
      address: "B-1/20, Ground Floor, Vasant Vihar, New Delhi 110057",
      phone: "+91-11-43425000",
      city: "New Delhi",
      fax: "+91-11-43425050",
    },
  },
  {
    label: "Ecuadorian",
    link: "ecuadorian",
    flag: "🇪🇨",
    key: 46,
    value: "Ecuador",
    code: "EC",
    address: {
      email: "eecuindia@mmrree.gob.ec",
      address: "Sultan Puri, Block E, Vasant Vihar, South West Delhi 110057",
      phone: "+011 2615 2264",
      fax: "+011 2615 2264",
      city: "New Delhi",
    },
  },
  {
    label: "Salvadoran",
    link: "salvadoran",
    flag: "🇸🇻",
    key: 48,
    value: "El Salvador",
    code: "SV",
    address: {
      email: "elsalvador-india@rree.gob.sv",
      address:
        "8, Munirka Marg, Block F, Vasant Vihar, South West Delhi 110057.",
      phone: "+91 114608 8400",
      fax: "",
      city: "New Delhi",
    },
  },
  {
    label: "Equatorial Guinean",
    link: "equatorial-guinean",
    flag: "🇬🇶",
    key: 49,
    value: "Equatorial Guinea",
    code: "GQ",
    address: {
      address:
        "Republic of Equatorial Guinea C-9/1 Vasant Vihar New Delhi 110057",
      phone: "41060146, 41060147 (O)",
      fax: "41060149",
      email: "embregeindiagmail.com",
      city: "New Delhi",
    },
  },
  {
    label: "Eritrean",
    link: "eritrean",
    flag: "🇪🇷",
    key: 50,
    value: "Eritrea",
    code: "ER",
    address: {
      email: "eriindia@yahoo.co.in",
      address: "C-7/9, Vasant Vihar South West Delhi 110057.",
      phone: "+91 11 26146336 ",
      fax: "+91-11-26146337",
      city: "New Delhi",
    },
  },
  {
    label: "Estonian",
    link: "estonian",
    flag: "🇪🇪",
    key: 51,
    value: "Estonia",
    code: "EE",
    address: {
      email: "embassy.delhi@mfa.ee",
      address: "C15, Malcha Marg, Chanakyapuri, New Delhi 110021.",
      city: "New Delhi",
      phone: "(+91) 11 4948 8650",
      fax: "",
    },
  },
  {
    label: "Eswatini",
    link: "eswatini",
    flag: "🇸🇿",
    key: 52,
    value: "Eswatini",
    code: "SZ",
    address: [],
  },
  {
    label: "Fijian",
    link: "fijian",
    flag: "🇫🇯",
    key: 54,
    value: "Fiji",
    code: "FJ",
    address: {
      country: "Fijian Consulate in New Delhi, India",
      address: "2/27 Ground Floor, Shanti Niketan, New Delhi 110021",
      city: "New Delhi",
      phone: "(91 11) 2687 6373 or (91 11) 26110101 Ext. 446/447",
      fax: "(91 11) 2611 0018",
      email: "fijihighcommission@yahoo.co.in",
    },
  },
  {
    label: "Finnish",
    link: "finnish",
    flag: "🇫🇮",
    key: 55,
    value: "Finland",
    code: "FI",
    address: {
      address: "E-3, Nyaya Marg, Chanakyapuri, New Delhi-110021",
      city: "New Delhi",
      phone: "+91-11-4149 7500",
      fax: "+91-11-4149 7555",
      email: "sanomat.nde@formin.fi",
    },
  },
  {
    label: "French",
    link: "french",
    flag: "🇫🇷",
    key: 56,
    value: "France",
    code: "FR",
    address: {
      country: "French Embassy in New Delhi, India",
      address: "2/50-E Shantipath, Chanakyapuri, New Delhi 110 021",
      city: "New Delhi",
      phone: "[91] (11) 2419 6100",
      fax: "[91] (11) 2419 6169",
      email: "webmaster@france-in-india.org",
    },
  },
  {
    label: "Gabonese",
    link: "gabonese",
    flag: "🇬🇦",
    key: 57,
    value: "Gabon",
    code: "GA",
    address: {
      email: "gabon.secretariat22@gmail.com",
      address: " E-84, Paschimi Marg, Vasant Vihar, New Delhi-110057, India",
      phone: "+91 11 41012513/15/16",
      fax: "+91 11 41012512",
      city: "New Delhi",
    },
  },
  {
    label: "Gambian",
    link: "gambian",
    flag: "🇬🇲",
    key: 58,
    value: "Gambia",
    code: "GM",
    address: {
      email: "gamhighcomdel@hotmail.com",
      address: "B-19, Vasant Marg, Vasant Vihar, South West Delhi 110057",
      phone: "+91 11 46120472",
      fax: "+91-11-46120471",
      city: "New Delhi",
    },
  },
  {
    label: "Georgian",
    link: "georgian",
    flag: "🇬🇪",
    key: 59,
    value: "Georgia",
    code: "GE",
    address: {
      email: "delhi.emb@mfa.gov.ge",
      address: "169 Jor Bagh, New Delhi - 110003",
      phone: " (+91) 11 4050 1424",
      fax: "",
      city: "New Delhi",
    },
  },
  {
    label: "German",
    link: "german",
    flag: "🇩🇪",
    key: 60,
    value: "Germany",
    code: "DE",
    address: {
      country: "German Embassy in New Delhi, India",
      address: "6/50G, Shanti Path, Chanakyapuri",
      city: "New Delhi",
      phone: "(00 91 11) 44 19 91 99",
      fax: "(0091 11) 26 87 31 17",
      email: "",
    },
  },
  {
    label: "Ghanaian",
    link: "ghanaian",
    flag: "🇬🇭",
    key: 61,
    value: "Ghana",
    code: "GH",
    address: {
      address: "50 N, Satya Marg, Chanakyapuri, New Delhi, Delhi 110021",
      email: "contact@ghana-mission.co.in ",
      phone: "+91-11-24193500, 24193502",
      fax: "+91-11-2688 3202",
      city: "New Delhi",
    },
  },
  {
    label: "Greek",
    link: "greek",
    flag: "🇬🇷",
    key: 62,
    value: "Greece",
    code: "GR",
    address: {
      country: "Greek Embassy in New Delhi, India",
      address:
        "EP-32, Dr. S. Radhakrishnan Marg, Chanakyapuri, New Delhi 110021",
      city: "New Delhi",
      phone: "(009111) 26880700-4",
      fax: "(009111) 26888010",
      email: "gremb.del@mfa.gr",
    },
  },
  {
    label: "Grenadian",
    link: "grenadian",
    flag: "🇬🇩",
    key: 63,
    value: "Grenada",
    code: "GD",
    address: {
      country: "Grenadian Consulate in New Delhi, India",
      address: "Honorary Consulate of Grenada in New Delhi, India",
      city: "New Delhi",
      phone: "91 11 33 13 370",
      fax: "91 11 33 28 307",
      email: "",
    },
  },
  {
    label: "Guatemalan",
    link: "guatemalan",
    flag: "🇬🇹",
    key: 64,
    value: "Guatemala",
    code: "GT",
    address: {
      address: "F-2/3, Ground Floor Vasant Vihar New Delhi-110057",
      email: "embaguateindia@minex.gob.gt",
      city: "New Delhi",
      phone: "\t+91 11-4699-9000",
      fax: "+91 11-4699-9015",
    },
  },
  {
    label: "Guinean",
    link: "guinean",
    flag: "🇬🇳",
    key: 65,
    value: "Guinea",
    code: "GN",
    address: {
      address: "\t26, Poorvi Marg Vasant Vihar New Delhi - 110057",
      email: "ambaguineedelhi@gmail.com",
      phone: "\t+91-11-4654 0211 and +91 11 4654 0213",
      fax: "+91-11-4654 4440",
      city: "New Delhi",
    },
  },
  {
    label: "Guyanese",
    link: "guyanese",
    flag: "🇬🇾",
    key: 67,
    value: "Guyana",
    code: "GY",
    address: {
      email: "hcommguy.del@gmail.com",
      address: " E2/13, E Block Market, Vasant Vihar, South West Delhi 110057.",
      phone: "+91-11-41669717, +91-11-41669718",
      fax: "",
      city: "New Delhi",
    },
  },
  {
    label: "Haitian",
    link: "haitian",
    flag: "🇭🇹",
    key: 68,
    value: "Haiti",
    code: "HT",
    address: {
      address:
        "Aerens Estate, Mall Road,Kishangarh Behind Pocket Diii Vasant Kunj, New Delhi-110070",
      email: "sanjeevaeren@gmail.com",
      phone: "+91 11 4765 4765",
      fax: "+91 11 4765 7766",
      city: "New Delhi",
    },
  },
  {
    label: "Honduran",
    link: "honduran",
    flag: "🇭🇳",
    key: 69,
    value: "Honduras",
    code: "HN",
    address: [],
  },
  {
    label: "Hungarian",
    link: "hungarian",
    flag: "🇭🇺",
    key: 70,
    value: "Hungary",
    code: "HU",
    address: {
      address: "2/50-M Niti Marg, Chanakyapuri, New Delhi – 110-021",
      city: "New Delhi",
      phone: "11-6114737",
      fax: "11-6886742",
      email: "mission.del@mfa.gov.hu",
    },
  },
  {
    label: "Icelandic",
    link: "icelandic",
    flag: "🇮🇸",
    key: 71,
    value: "Iceland",
    code: "IS",
    address: {
      email: "newdelhi@mfa.is",
      address: "10, Munirka Marg, Vasant Vihar, South West Delhi 110057",
      phone: "+91 011 4353 0300, +91-11-4240-3001",
      city: "New Delhi",
      fax: "",
    },
  },
  {
    label: "Indonesian",
    link: "indonesian",
    flag: "🇮🇩",
    key: 73,
    value: "Indonesia",
    code: "ID",
    address: {
      address: "50-A Kautilya Marg, Chanakyapuri, New Delhi 110021",
      city: "New Delhi",
      phone: "(91-11) 2611-8642 to 46",
      fax: "(91-11) 2687-4402, 2688-6763",
      email: "iembassy@giasdl01.vsnl.net.in",
    },
  },
  {
    label: "Irish",
    link: "irish",
    flag: "🇮🇪",
    key: 76,
    value: "Ireland",
    code: "IE",
    address: {
      country: "Irish Embassy in New Delhi, India",
      address: "Embassy of Ireland in India",
      city: "New Delhi",
      phone: "+91-11-2462-6733/741/743",
      fax: "+91-11-2469-7053",
      email: "newdelhiembassy@dfa.ie",
    },
  },
  {
    label: "Israeli",
    link: "israeli",
    flag: "🇮🇱",
    key: 77,
    value: "Israel",
    code: "IL",
    address: {
      country: "Israeli Embassy in New Delhi, India",
      address:
        "3, Dr APJ Abdul Kalam Rd, Aurangzeb Road, New Delhi, Delhi 110011, India",
      city: "New Delhi",
      phone: "0091-11-30414500",
      fax: "0091-11-30414555",
      email: "info@newdelhi.mfa.gov.il",
    },
  },
  {
    label: "Italian",
    link: "italian",
    flag: "🇮🇹",
    key: 78,
    value: "Italy",
    code: "IT",
    address: {
      country: "Italian Embassy in New Delhi, India",
      address: "50-E Chandragupta Marg, Chanakyapuri, New Delhi -110021",
      city: "New Delhi",
      phone: "+91 11 2611 4355",
      fax: "+91 11 2687 3889",
      email: "visti.ambnewdelhi@esteri.it",
    },
  },
  {
    label: "Jamaican",
    link: "jamaican",
    flag: "🇯🇲",
    key: 80,
    value: "Jamaica",
    code: "JM",
    address: {
      address: "B-9/1, Ground Floor, Vasant Vihar, New Delhi 110057.",
      city: "New Delhi",
      phone: "2335 5411/2341 7122",
      fax: "011 2335 5432/2341 6275",
      email: "Khemka@del3.vsnl.net.in",
    },
  },
  {
    label: "Japanese",
    link: "japanese",
    flag: "🇯🇵",
    key: 81,
    value: "Japan",
    code: "JP",
    address: {
      country: "Japanese Embassy in New Delhi, India",
      address: "Plot No.4&5, 50-G Shantipath, Chanakyapuri, New Delhi 110021",
      city: "New Delhi",
      phone: "(+91-11) 2687-6564, 2687-6581",
      fax: "+91-11-2688-5587",
      email: "jpemb-visa@nd.mofa.go.jp",
    },
  },
  {
    label: "Jordanian",
    link: "jordanian",
    flag: "🇯🇴",
    key: 82,
    value: "Jordan",
    code: "JO",
    address: {
      country: "Jordanian Embassy in New Delhi, India",
      address:
        " N14, August Kranti Marg, Panchsheel Park North, Panchsheel Park, New Delhi 110017",
      city: "New Delhi",
      phone: "(009111)24653318 - 246533099",
      fax: "00911124653353",
      email: "jordan@jordanembassyindia.org",
    },
  },
  {
    label: "Kazakhstani",
    link: "kazakhstani",
    flag: "🇰🇿",
    key: 83,
    value: "Kazakhstan",
    code: "KZ",
    address: {
      address: "F6/7, Vasant Vihar, New Delhi, 110057",
      city: "New Delhi",
      phone: "(91-11) 46007700",
      fax: "(91-11) 46007701",
      email: "embassy@kazind.com",
    },
  },
  {
    label: "Kenyan",
    link: "kenyan",
    flag: "🇰🇪",
    key: 84,
    value: "Kenya",
    code: "KE",
    address: {
      country: "Kenyan Consulate in New Delhi, India",
      address: "A15/14, Vasant Vihar, New Delhi, 110057.",
      city: "New Delhi",
      phone: "+ 91 11 26146537/38/40",
      fax: "+ 91 11 26146550",
      email: "info@kenyamission-delhi.com",
    },
  },
  {
    label: "Kiribati",
    link: "kiribati",
    flag: "🇰🇮",
    key: 85,
    value: "Kiribati",
    code: "KI",
    address: {
      address: "1220, DLF Tower A, 12th Floor, Jasola, New Delhi 110025",
      email: "honoraryconsul@kiribatiindia.com",
      phone: "11-42224900",
      fax: "",
      city: "New Delhi",
    },
  },
  {
    label: "Kyrgyzstani",
    link: "kyrgyzstani",
    flag: "🇰🇬",
    key: 87,
    value: "Kyrgyzstan",
    code: "KG",
    address: {
      country: "Kyrgyzstani Embassy in New Delhi, India",
      address: " D 2/2, Vasant Vihar, New Delhi-110057.",
      city: "New Delhi",
      phone: "(+91-11) 24108008",
      fax: "(+91-11) 24108009",
      email: "kyrghyz@netscape.net",
    },
  },
  {
    label: "Lao",
    link: "lao",
    flag: "🇱🇦",
    key: 88,
    value: "Laos",
    code: "LA",
    address: {
      country: "Lao or Laotian Embassy in New Delhi, India",
      address:
        "S-420, M Block Rd, Block S, Greater Kailash II, Greater Kailash, New Delhi 110048",
      city: "New Delhi",
      phone: "(+91) 11-2693 3320 or 3319",
      fax: "(+91) 11-2632 3048",
      email: "amblaodl@ndb.vsnl.net.in",
    },
  },
  {
    label: "Latvian",
    link: "latvian",
    flag: "🇱🇻",
    key: 89,
    value: "Latvia",
    code: "LV",
    address: {
      country: "Latvian Consulate in New Delhi, India",
      address: "B8 Anand Niketan, New Delhi 110021, Delhi, India",
      city: "New Delhi",
      phone: "(+91-11) 26112931",
      fax: "(+91-11) 26113753",
      email: "",
    },
  },
  {
    label: "Lesotho",
    link: "lesotho",
    flag: "🇱🇸",
    key: 91,
    value: "Lesotho",
    code: "LS",
    address: {
      email: "lesothonewdelhi@gmail.com",
      address: "Block E, Vasant Vihar, New Delhi, Delhi, India",
      phone: "+91114660713",
      city: "New Delhi",
      fax: "",
    },
  },
  {
    label: "Liberian",
    link: "liberian",
    flag: "🇱🇷",
    key: 92,
    value: "Liberia",
    code: "LR",
    address: {
      address:
        "The Roseate New Delhi Natinal Highway 8, Samalkha New Delhi-110037",
      city: "New Delhi",
      phone: "\t+91 11-4133 6606",
      fax: "(+91) 22-2648 1889",
      email: "info@honconsulgeneralliberia.in",
    },
  },
  {
    label: "Liechtenstein",
    link: "liechtenstein",
    flag: "🇱🇮",
    key: 94,
    value: "Liechtenstein",
    code: "LI",
    address: [],
  },
  {
    label: "Lithuanian",
    link: "lithuanian",
    flag: "🇱🇹",
    key: 95,
    value: "Lithuania",
    code: "LT",
    address: {
      email: "amb.in@urm.lt",
      address: "E-4/3 Vasant Vihar, New Delhi 110057",
      phone: "+91 11 4313 2200",
      fax: "+91 11 4313 2222",
      city: "New Delhi",
    },
  },
  {
    label: "Luxembourgish",
    link: "luxembourgish",
    flag: "🇱🇺",
    key: 96,
    value: "Luxembourg",
    code: "LU",
    address: {
      email: "Newdelhi.Amb@mae.etat.lu",
      address: "84 Jor Bagh, New Delhi 110003",
      phone: " (+91) 11 49 98 66 00.",
      city: "New Delhi",
      fax: "",
    },
  },
  {
    label: "Malagasy",
    link: "malagasy",
    flag: "🇲🇬",
    key: 98,
    value: "Madagascar",
    code: "MG",
    address: {
      email: "contact@madagascar-embassy.in",
      address:
        "18, Ground Floor, Mayfair Gardens, August Kranti Marg, New Delhi 110016",
      phone: "(+91) 11-4106 7747",
      fax: "(+91) 11-6617 3222.",
      city: "New Delhi",
    },
  },
  {
    label: "Malawian",
    link: "malawian",
    flag: "🇲🇼",
    key: 99,
    value: "Malawi",
    code: "MW",
    address: {
      address: "Malawi High Commission D-106, Anand Niketan, New Delhi 110021",
      fax: "\t011 24116010",
      phone: "+91 11 26706000",
      email: "malawihcindia@gmail.com",
      city: "New Delhi",
    },
  },
  {
    label: "Malaysian",
    link: "malaysian",
    flag: "🇲🇾",
    key: 100,
    value: "Malaysia",
    code: "MY",
    address: {
      address:
        "50-M, Satya Marg, Chanakyapuri, New Delhi, Delhi (NCT) - 110021",
      city: "New Delhi",
      phone: "91-11-261 11 291/92/93/97",
      fax: "91-11-268 81 538",
      email: "maldelhi@kln.gov.my",
    },
  },
  {
    label: "Malian",
    link: "malian",
    flag: "🇲🇱",
    key: 102,
    value: "Mali",
    code: "ML",
    address: {
      address: "A2/29, Block A 2, Safdarjung Enclave, South West Delhi 110029",
      city: "New Delhi",
      phone: "+91 11 41 09 0624",
      fax: "",
      email: "ambamalidelhi@maliembassy.co.in",
    },
  },
  {
    label: "Maltese",
    link: "maltese",
    flag: "🇲🇹",
    key: 103,
    value: "Malta",
    code: "MT",
    address: {
      country: "Maltese Consulate in New Delhi, India",
      address:
        "The Executive Centre India, Level 1 & 2, Crescent Building, Lado Sarai, Mehrauli New Delhi 110030 India",
      city: "New Delhi",
      phone: "+91 11 2649 4961-5",
      fax: "+91 11 2649 4966",
      email: "maltahighcommission.newdelhi@gov.mt",
    },
  },
  {
    label: "Marshallese",
    link: "marshallese",
    flag: "🇲🇭",
    key: 104,
    value: "Marshall Islands",
    code: "MH",
    address: {
      address:
        "C-49, G-Block, Bandra Kurla Complex Bandra East Mumbai 400051 Maharashtra India",
      phone: "++91 22 2672 4000",
      fax: "",
      city: "Mumbai",
      email: "",
    },
  },
  {
    label: "Mauritian",
    link: "mauritian",
    flag: "🇲🇺",
    key: 106,
    value: "Mauritius",
    code: "MU",
    address: {
      country: "Mauritian Embassy in New Delhi, India",
      address: "EP-41 Jesus & Mary Marg Chanakyapuri New Delhi 110021",
      city: "New Delhi",
      phone: "+91 11 24102161 or +91 11 24102162",
      fax: "",
      email: "mhcnd@bol.net.in",
    },
  },
  {
    label: "Mexican",
    link: "mexican",
    flag: "🇲🇽",
    key: 107,
    value: "Mexico",
    code: "MX",
    address: {
      country: "Mexican Embassy in New Delhi, India",
      address: " C-8, Anand Niketan, New Delhi, 110021, India.",
      city: "New Delhi",
      phone: "(91-11) 2411-7180, 2411-7181, 2411-7182, 2411-7183",
      fax: "(91-11) 2411-7193",
      email: "embamexindia@airtelmail.in",
    },
  },
  {
    label: "Micronesian",
    link: "micronesian",
    flag: "🇫🇲",
    key: 108,
    value: "Micronesia",
    code: "FM",
    address: [],
  },
  {
    label: "Moldovan",
    link: "moldovan",
    flag: "🇲🇩",
    key: 109,
    value: "Moldova",
    code: "MD",
    address: {
      address:
        "Bhageria House, 43, Community Centre, New Friends Colony, New Delhi 110025",
      phone: "+91 11 4950 2068",
      email: "contact@consulateofmoldova.in",
      fax: "",
      city: "New Delhi",
    },
  },
  {
    label: "Monégasque",
    link: "monégasque",
    flag: "🇲🇨",
    key: 110,
    value: "Monaco",
    code: "MC",
    address: {
      email: "kpsingh@dlfgroup.in",
      address: "5, Sansad Marg, Janpath, Connaught Place, New Delhi 110001",
      phone: "+91 11 4150 2150, +91 11 4150 2149",
      fax: "",
      city: "New Delhi",
    },
  },
  {
    label: "Mongolian",
    link: "mongolian",
    flag: "🇲🇳",
    key: 111,
    value: "Mongolia",
    code: "MN",
    address: {
      country: "Mongolian Embassy in New Delhi, India",
      address: "34, Golf Links, New Delhi, Delhi (NCT) - 110003",
      city: "New Delhi",
      phone: "0091-11-4631728, 4717989",
      fax: "0091-11-4633240",
      email: "mongemb@vsnl.net",
    },
  },
  {
    label: "Montenegrin",
    link: "montenegrin",
    flag: "🇲🇪",
    key: 112,
    value: "Montenegro",
    code: "ME",
    address: {
      address: "S 528, Greater Kailash Part 1 New Delhi 110048 India",
      email: "janisdarbari1@yahoo.com",
      phone: "(+91) 11 2923 8909",
      fax: "",
      city: "New Delhi",
    },
  },
  {
    label: "Moroccan",
    link: "moroccan",
    flag: "🇲🇦",
    key: 113,
    value: "Morocco",
    code: "MA",
    address: {
      email: "embassyofmorocco@rediffmail.com",
      address: "C-7/5, Vasant Vihar, South West Delhi 110057, India",
      phone: "+91 11 4056 4257",
      fax: "",
      city: "New Delhi",
    },
  },
  {
    label: "Mozambican",
    link: "mozambican",
    flag: "🇲🇿",
    key: 114,
    value: "Mozambique",
    code: "MZ",
    address: {
      address:
        "Embassy of Mozambique,6/4 Shantiniketan Near, Anand Niketan, New Delhi India",
      city: "New Delhi",
      phone: "(+91-11) 22615666",
      fax: "(+91-11) 22615666",
      email: "",
    },
  },
  {
    label: "Namibian",
    link: "namibian",
    flag: "🇳🇦",
    key: 115,
    value: "Namibia",
    code: "NA",
    address: {
      country: "Namibian Consulate in New Delhi, India",
      address: "B-9/6 Vasant Vihar, New Delhi, 110057 New Delhi, India",
      city: "New Delhi",
      phone: "+91-11-614 0389",
      fax: "+91-11-614 6120",
      email: "nhcdelhi@del2.vsnl.net.in",
    },
  },
  {
    label: "Nauruan",
    link: "nauruan",
    flag: "🇳🇷",
    key: 116,
    value: "Nauru",
    code: "NR",
    address: {
      address: "S-327, Greater Kailash I New Delhi-110048 India",
      city: "New Delhi",
      phone: "(+91-11) 26215780, 26414744",
      fax: "(+91-11) 26215778",
      email: "kartarbhalla@mantraonline.com",
    },
  },
  {
    label: "Dutch",
    link: "dutch",
    flag: "🇳🇱",
    key: 118,
    value: "Netherlands",
    code: "NL",
    address: {
      country: "Dutch Embassy in New Delhi, India",
      address: "6/50 F, Shantipath Chanakyapuri New Delhi - 110021",
      city: "New Delhi",
      phone: "+91-11-24197600",
      fax: "+91-11-24197710",
      email: "nde@minbuza.nl",
    },
  },
  {
    label: "New Zealander",
    link: "new-zealander",
    flag: "🇳🇿",
    key: 119,
    value: "New Zealand",
    code: "NZ",
    address: {
      email: "nzhcindia@mfat.net",
      address:
        "Sir Edmund Hillary Marg, Chanakyapuri, New Delhi, Delhi (NCT) - 110021",
      phone: "+91-11-46883170",
      fax: "",
      city: "New Delhi",
    },
  },
  {
    label: "Nicaraguan",
    link: "nicaraguan",
    flag: "🇳🇮",
    key: 120,
    value: "Nicaragua",
    code: "NI",
    address: {
      address: "43-A, Prithviraj Road New Delhi-110011 India",
      phone: "+91-11-24694469/24618238",
      fax: "+91-11-24649199",
      email: "vcbdabur.com",
      city: "New Delhi",
    },
  },
  {
    label: "Norwegian",
    link: "norwegian",
    flag: "🇳🇴",
    key: 125,
    value: "Norway",
    code: "NO",
    address: {
      address: " 50-C, Shantipath, Chanakyapuri, New Delhi - 110021",
      city: "New Delhi",
      phone: "91 - 11 - 41779200",
      fax: "91 - 11 - 41617815(For Visa) , 91 - 11 - 41680145",
      email: "emb.newdelhi@mfa.no",
    },
  },
  {
    label: "Omani",
    link: "omani",
    flag: "🇴🇲",
    key: 126,
    value: "Oman",
    code: "OM",
    address: {
      address: "EP 10 & 11, Chandragupta Marg, Chankyapuri, New Delhi 21",
      city: "New Delhi",
      phone: "(+91) 11-2688 5622",
      fax: "(+91) 11-2688 5621",
      email: "",
    },
  },
  {
    label: "Palauan",
    link: "palauan",
    flag: "🇵🇼",
    key: 128,
    value: "Palau",
    code: "PW",
    address: {
      email: "mission@palauan.org",
      address: "C2/258, Janakpuri, New Delhi - 110058",
      city: "New Delhi",
      phone: "+91-11-40109565, +91-9667825200",
      fax: "",
    },
  },
  {
    label: "Palestinian",
    link: "palestinian",
    flag: "🇵🇸",
    key: 129,
    value: "Palestine",
    code: "PS",
    address: {
      country: "Palestinian Embassy in New Delhi, India",
      address:
        "EP, 29-B Diplomatic Enclave, Chanakyapuri, New Delhi, Delhi (NCT) - 110021",
      city: "New Delhi",
      phone: "9111-6146605/4679115/4676605",
      fax: "9111-6142942/6872943",
      email: "embassy71@gmail.com",
    },
  },
  {
    label: "Panamanian",
    link: "panamanian",
    flag: "🇵🇦",
    key: 130,
    value: "Panama",
    code: "PA",
    address: {
      country: "Panamanian Embassy in New Delhi, India",
      address: "Embassy of Panama in New Delhi, India",
      city: "New Delhi",
      phone: "(+91) 11-2433 2684 / 5627",
      fax: "(+91) 11-2433 5631",
      email: "",
    },
  },
  {
    label: "Papua New Guinean",
    link: "papua-new-guinean",
    flag: "🇵🇬",
    key: 131,
    value: "Papua New Guinea",
    code: "PG",
    address: {
      email: "kundund@pnghcdelhi.in",
      address: "90, Vasant Vihar, Poorvi Marg, South West Delhi 110057",
      city: "New Delhi",
      phone: "+91 11 4601 2815",
      fax: "",
    },
  },
  {
    label: "Paraguayan",
    link: "paraguayan",
    flag: "🇵🇾",
    key: 132,
    value: "Paraguay",
    code: "PY",
    address: {
      address:
        "B-12, SECOND FLOOR, VASANT MARG, VASANT VIHAR, NEW DELHI – 110057 INDIA.",
      phone: "+91-11-42705671",
      fax: "91-11-42705672",
      email: "indiaembaparsec@outlook.com",
      city: "New Delhi",
    },
  },
  {
    label: "Peruvian",
    link: "peruvian",
    flag: "🇵🇪",
    key: 133,
    value: "Peru",
    code: "PE",
    address: {
      country: "Peruvian Embassy in New Delhi, India",
      address: "D-2/5, Vasant Vihar, New Delhi 110057 India",
      city: "New Delhi",
      phone: "+91-11-2614-1154",
      fax: "+91-11-2631-2557 ; +91-11-2614-1155",
      email: "info@embaperuindia.com",
    },
  },
  {
    label: "Filipino",
    link: "filipino",
    flag: "🇵🇭",
    key: 134,
    value: "Philippines",
    code: "PH",
    address: {
      address: "50-N, Nyaya Marg, Chanakyapuri, New Delhi-110021 India",
      city: "New Delhi",
      phone: "(+91) 11 2410-1120 or 11 2688-9091",
      fax: "(+91) 11 2687-6401",
      email: "newdelhipe@bol.net.in",
    },
  },
  {
    label: "Polish",
    link: "polish",
    flag: "🇵🇱",
    key: 135,
    value: "Poland",
    code: "PL",
    address: {
      email: "newdelhi.polemb.info@msz.gov.pl",
      address: "50-M, Shantipath, Chanakyapuri, New Delhi India",
      city: "New Delhi",
      phone: "+91 11 4149 6900",
      fax: "",
    },
  },
  {
    label: "Portuguese",
    link: "portuguese",
    flag: "🇵🇹",
    key: 136,
    value: "Portugal",
    code: "PT",
    address: {
      address: "No.4, Panchsheel Marg Chanakyapuri Nova Deli 110021",
      email: "visas.novadeli@mne.pt",
      phone: "(91) 11 4607 1001",
      fax: "",
      city: "New Delhi",
    },
  },
  {
    label: "Romanian",
    link: "romanian",
    flag: "🇷🇴",
    key: 138,
    value: "Romania",
    code: "RO",
    address: {
      address: "3/6 Shanti Niketan, New Delhi 110021, India",
      city: "New Delhi",
      phone: "(00) (91) (11) 26140447 or 26140700",
      fax: "(00) (91) (11) 26140611",
      email: "embrom@touchtelindia.net",
    },
  },
  {
    label: "Russian",
    link: "russian",
    flag: "🇷🇺",
    key: 139,
    value: "Russia",
    code: "RU",
    address: {
      country: "Russian Embassy in New Delhi, India",
      address: "Shantipath, Chanakyapuri, New Delhi, Delhi 110021, India",
      city: "New Delhi",
      phone: "+9111 2611-0640, 2611-0641, 2611-0642, 2611-0644,",
      fax: "+9111 2687-6823, 2410-3961",
      email: "indrusem@del2.vsnl.net.in",
    },
  },
  {
    label: "Rwandan",
    link: "rwandan",
    flag: "🇷🇼",
    key: 140,
    value: "Rwanda",
    code: "RW",
    address: {
      country: "Rwandan Embassy in New Delhi, India",
      address:
        " L-1/2, Kausalya Park, Block L1, Hauz Khas Enclave, Hauz Khas, South West Delhi 110016 India",
      city: "New Delhi",
      phone: "(+91-11) 51661604",
      fax: "(+91-11) 51661525",
      email: "ambadelhi@minaffet.gov.rw",
    },
  },
  {
    label: "Saint Lucian",
    link: "saint-lucian",
    flag: "🇱🇨",
    key: 142,
    value: "Saint Lucia",
    code: "LC",
    address: {
      email: "saintluciaindia@gmail.com",
      address: "Shantipath Chanakyapuri, South West Delhi 110021 ",
      phone: "",
      fax: "+91-011-2687-0062 ",
      city: "New Delhi",
    },
  },
  {
    label: "Samoan",
    link: "samoan",
    flag: "🇼🇸",
    key: 144,
    value: "Samoa",
    code: "WS",
    address: [],
  },
  {
    label: "Sanmarinese",
    link: "sanmarinese",
    flag: "🇸🇲",
    key: 145,
    value: "San Marino",
    code: "SM",
    address: {
      address:
        " 12, Dr APJ Abdul Kalam Rd, South Avenue Lane Area, Tughlak Road Area, New Delhi 110011, India",
      city: "New Delhi",
      phone: "(+91-11) 223016675/ (+91-11) 2301-5850",
      fax: "(+91-11) 2301-9677",
      email: "bhaims@ndb.yshl.net.it",
    },
  },
  {
    label: "Saudi",
    link: "saudi",
    flag: "🇸🇦",
    key: 147,
    value: "Saudi Arabia",
    code: "SA",
    address: {
      address: "EP 30 Chandragupta Marg, Chanakya Puri, New Delhi-110021 India",
      city: "New Delhi",
      phone: "91-11-26144102 / 91-11-26144073/+91-11-26144083",
      fax: "91-11-26144244 / 91-11-26144201",
      email: "",
    },
  },
  {
    label: "Senegalese",
    link: "senegalese",
    flag: "🇸🇳",
    key: 148,
    value: "Senegal",
    code: "SN",
    address: {
      country: "Senegalese Embassy in New Delhi, India",
      address:
        "C 6/10, Vasant Vihar, Near C Block market, South West Delhi 110057 India",
      city: "New Delhi",
      phone: "(+91-11) 6147687 / +91-11-6147025",
      fax: "(+91-11) 26142422",
      email: "",
    },
  },
  {
    label: "Serbian",
    link: "serbian",
    flag: "🇷🇸",
    key: 149,
    value: "Serbia",
    code: "RS",
    address: {
      address: "3/50G, Niti Marg, Chanakyapuri, New Delhi, 110021, India.",
      city: "New Delhi",
      phone: "+91-11-26873661 / +91-11-26872073",
      fax: "+91-11-26885535",
      email: "embscgdelhi@vsnl.net",
    },
  },
  {
    label: "Seychellois",
    link: "seychellois",
    flag: "🇸🇨",
    key: 150,
    value: "Seychelles",
    code: "SC",
    address: {
      country: "Seychelles Consulate in Mumbai (Bombay), India",
      address: "Honorary Consulate of Syechelles in Bombay, India",
      city: "Mumbai (Bombay)",
      phone: "(+91-22) 252l4360",
      fax: "(+91-22) 25210936",
      email: "ominicd@bm4.vsnl.net.in",
    },
  },
  {
    label: "Sierra Leonean",
    link: "sierra-leonean",
    flag: "🇸🇱",
    key: 151,
    value: "Sierra Leone",
    code: "SL",
    address: {
      country: "Sierra Leonean Consulate in Mumbai 400021, India",
      address: "Consulate of Sierra Leone in India",
      city: "Mumbai 400021",
      phone: "+91-22 22852617",
      fax: "+91-22 22880815",
      email: "",
    },
  },
  {
    label: "Singaporean",
    link: "singaporean",
    flag: "🇸🇬",
    key: 152,
    value: "Singapore",
    code: "SG",
    address: {
      address:
        "152, 14th Floor, Maker Chambers IV, 222 Jamnalal Bajaj Road, Nariman Point, Mumbai 400-021, India",
      city: "Mumbai",
      phone: "(91 22) 2204 3205",
      fax: "(91 22) 2285 5812",
      email: "singcon_bom@sgmfa.gov.sg",
    },
  },
  {
    label: "Slovak",
    link: "slovak",
    flag: "🇸🇰",
    key: 153,
    value: "Slovakia",
    code: "SK",
    address: {
      country: "Slovak Embassy in New Delhi, India",
      address: "Embassy of the Slovak Republic in New Delhi, India",
      city: "New Delhi",
      phone: "(+91) 11 2688 9071",
      fax: "(+91) 11 2687 7941",
      email: "skdelhi@giasdl01.vsnl.net.in",
    },
  },
  {
    label: "Slovenian",
    link: "slovenian",
    flag: "🇸🇮",
    key: 154,
    value: "Slovenia",
    code: "SI",
    address: {
      address: "A-5/4, Block A, Vasant Vihar, New Delhi 110057.",
      city: "New Delhi",
      phone: "+91-11-51662891",
      fax: "+91-11-51662895",
      email: "vnd@mzz-dkp.sigov.si",
    },
  },
  {
    label: "Solomon Islander",
    link: "solomon-islander",
    flag: "🇸🇧",
    key: 155,
    value: "Solomon Islands",
    code: "SB",
    address: {
      address: "\tE-9, Connaught House, Connaught Place, New Delhi-110001",
      city: "New Delhi",
      phone: "+91 11 4151 7279, +91 11 3955 5506",
      fax: "\t+91 11 2341 2313",
      email: "rb@bird.in",
    },
  },
  {
    label: "South African",
    link: "south-african",
    flag: "🇿🇦",
    key: 157,
    value: "South Africa",
    code: "ZA",
    address: {
      address: "B-18 Vasant Marg, Vasant Vihar, New Delhi, India 110057, India",
      city: "New Delhi",
      phone: "91-11-2614 9411 - 20",
      fax: "+91-11-2614 3605",
      email: "highcommissioner@sahc-india.com",
    },
  },
  {
    label: "Spanish",
    link: "spanish",
    flag: "🇪🇸",
    key: 160,
    value: "Spain",
    code: "ES",
    address: {
      address: "12, Prithviraj Rd, Aurangzeb Road, New Delhi, Delhi 110011",
      city: "New Delhi",
      phone: "(+91) (11) 4129 3000",
      fax: "(+91) (11) 4129 3020",
      email: "embespin@mail.mae.es",
    },
  },
  {
    label: "Sri Lankan",
    link: "sri-lankan",
    flag: "🇱🇰",
    key: 161,
    value: "Sri Lanka",
    code: "LK",
    address: {
      address: "27, Kautilya Marg, Chanakyapuri, New Delhi, India",
      city: "New Delhi",
      phone: "(+91-11) 3010201/3/+91-11-2301-7498",
      fax: "+91-11-2379-3604",
      email: "lankacom@del2.vsnl.net.in",
    },
  },
  {
    label: "Surinamese",
    link: "surinamese",
    flag: "🇸🇷",
    key: 163,
    value: "Suriname",
    code: "SR",
    address: {
      address:
        "Embassy of the Republic of Suriname A-13/8, Ground Floor Vasant Vihar New Delhi-110057",
      email: "amb.indiaforeignaffairs.gov.sr",
      fax: "+91-11-2688 8450",
      phone: "+91-11-4552 3733, 4565 7553",
      city: "New Delhi",
    },
  },
  {
    label: "Swedish",
    link: "swedish",
    flag: "🇸🇪",
    key: 164,
    value: "Sweden",
    code: "SE",
    address: {
      address: "4-5 Nyaya Marg, Chanakyapuri, New Delhi 110 021, India",
      city: "New Delhi",
      phone: "3.30 to 4 p.m.",
      fax: "+91 (11) 268 854 01",
      email: "ambassaden.new-delhi@foreign.ministry.se",
    },
  },
  {
    label: "Swiss",
    link: "swiss",
    flag: "🇨🇭",
    key: 165,
    value: "Switzerland",
    code: "CH",
    address: {
      address: "E-3, Nyaya Marg, Chanakyapuri, New Delhi 110 021, India",
      city: "New Delhi",
      phone: "(+91 11) 2687 8372",
      fax: "(+91 11) 26873093",
      email: "ndh.vertretung@eda.admin.ch",
    },
  },
  {
    label: "Taiwanese",
    link: "taiwanese",
    flag: "🇹🇼",
    key: 167,
    value: "Taiwan",
    code: "TW",
    address: {
      address:
        "Address No. 34, Paschimi Marg, Vasant Vihar, New Delhi 110057, India",
      city: "New Delhi",
      phone: "(002-91-11)4166-2700 -2",
      fax: "(002-91-11)2 614-8480",
      email: "ind@mofa.gov.tw",
    },
  },
  {
    label: "Tajikistani",
    link: "tajikistani",
    flag: "🇹🇯",
    key: 168,
    value: "Tajikistan",
    code: "TJ",
    address: {
      country: "Tajikistani Embassy in New Dehli, India",
      address: "A-4/2, Block A, Vasant Vihar, New Delhi, Delhi 110057",
      city: "New Delhi",
      phone: "+91-11-2615-4282",
      fax: "+91-11-2615-4282",
      email: "tajembindia@yahoo.com",
    },
  },
  {
    label: "Tanzanian",
    link: "tanzanian",
    flag: "🇹🇿",
    key: 169,
    value: "Tanzania",
    code: "TZ",
    address: {
      address:
        "United Republic Of Tanzania Embassy, EP, 15C, Chandragupta Marg, Malcha, New Delhi, Delhi 110021",
      city: "New Delhi",
      phone: "(91-11) 6853046-7, 6968409, 6968406-7",
      fax: "(91-11) 6968410",
      email: "tanzrep@del2.vsnl.net.in",
    },
  },
  {
    label: "Thai",
    link: "thai",
    flag: "🇹🇭",
    key: 170,
    value: "Thailand",
    code: "TH",
    address: {
      country: "Thai Embassy in New Delhi, India",
      address:
        "Royal Thai Embassy in New Delhi, India Visa and Consular section :",
      city: "New Delhi",
      phone: "(91-11) 2611-8103 and/or 2611-8104",
      fax: "(91-11) 2687-2029, 26883235",
      email: "thaidel@mfa.go.th",
    },
  },
  {
    label: "Togolese",
    link: "togolese",
    flag: "🇹🇬",
    key: 171,
    value: "Togo",
    code: "TG",
    address: {
      address: "D-4/6, Block D, Vasant Vihar, New Delhi, Delhi 110057",
      citu: "New Delhi",
      phone: "011 4103 7036",
      email: "",
      fax: "",
    },
  },
  {
    label: "Tongan",
    link: "tongan",
    flag: "🇹🇴",
    key: 172,
    value: "Tonga",
    code: "TO",
    address: {
      address: "C 59, Panchsheel Enclave, P.O. Box 4070, New Delhi 110017",
      phone: "+91 98 1058 3949",
      email: "deshsahae@yahoo.com",
      fax: "",
      city: "New Delhi",
    },
  },
  {
    label: "Tuvaluan",
    link: "tuvaluan",
    flag: "🇹🇻",
    key: 177,
    value: "Tuvalu",
    code: "TV",
    address: {
      address:
        "BN-8, Shaheed Udham Singh Marg, Block BN, Poorbi Shalimar Bag, Shalimar Bagh, Delhi, 110088",
      phone: "+91 7840890607",
      email: "tuvaluconsulateindia@gmail.com",
      fax: "",
      city: "New Delhi",
    },
  },
  {
    label: "Ugandan",
    link: "ugandan",
    flag: "🇺🇬",
    key: 178,
    value: "Uganda",
    code: "UG",
    address: {
      address: "B3/14, Block B, Vasant Vihar, New Delhi, Delhi 110057",
      city: "New Delhi",
      phone: "(+91-11) 26144413, 26145817",
      fax: "(+91-11) 26144405",
      email: "ughcom@vsnl.net.in",
    },
  },
  {
    label: "Ukrainian",
    link: "ukrainian",
    flag: "🇺🇦",
    key: 179,
    value: "Ukraine",
    code: "UA",
    address: {
      address: "C-6/5, Vasant Vihar, New Delhi, India, 110 057",
      city: "New Delhi",
      phone: "+91-11-6146041 / +91-11-6146042",
      fax: "+91-11-6146043 / +91-11-6146103",
      email: "emb_in@mfa.gov.ua",
    },
  },
  {
    label: "British",
    link: "british",
    flag: "🇬🇧",
    key: 181,
    value: "United Kingdom",
    code: "GB",
    address: {
      address: "Shantipath, Chanakyapuri, New Delhi, Delhi 110021",
      city: "New Delhi",
      phone: "(91) (11) 2687 2161",
      fax: "(91) (11) 2687 2882",
      email: "postmaster.NEDEL@fco.gov.uk",
    },
  },
  {
    label: "Uruguayan",
    link: "uruguayan",
    flag: "🇺🇾",
    key: 183,
    value: "Uruguay",
    code: "UY",
    address: {
      address: "B-8/3, Block B, Vasant Vihar, New Delhi, Delhi 110057",
      city: "New Delhi",
      phone: "(+91-11-2615) 1991 / 1992 / 1993",
      fax: "+91-11-2614 4306",
      email: "uruind@del3.vsnl.net.in",
    },
  },
  {
    label: "Uzbekistani",
    link: "uzbekistani",
    flag: "🇺🇿",
    key: 184,
    value: "Uzbekistan",
    code: "UZ",
    address: {
      address:
        "EP-40, Dr. S. Radhakrishna Marg, Chanakyapuri, New Delhi, Delhi 110021",
      city: "New Delhi",
      phone: "(+91-11)-2467-0774 / 2467-0775 / 2410 5640",
      fax: "+91-11-2467-0773",
      email: "uzembind@vsnl.com",
    },
  },
  {
    label: "Vanuatuan",
    link: "vanuatuan",
    flag: "🇻🇺",
    key: 185,
    value: "Vanuatu",
    code: "VU",
    address: {
      address: "28, Friends Colony (West), New Delhi 110065",
      phone: "+91 11 4658 8237, +91 11 4658 8236",
      email: "vikram.kapur@sify.com",
      fax: "",
      city: "New Delhi",
    },
  },
  {
    label: "Venezuelan",
    link: "venezuelan",
    flag: "🇻🇪",
    key: 186,
    value: "Venezuela",
    code: "VE",
    address: {
      city: "New Delhi",
      address:
        "D Block 1/14 G.F Vasant Vihar New Delhi South West Delhi 110057 Delhi India",
      phone: "+91 11 4168 0219",
      email: "",
      fax: "",
    },
  },
  {
    label: "Vietnamese",
    link: "vietnamese",
    flag: "🇻🇳",
    key: 187,
    value: "Vietnam",
    code: "VN",
    address: {
      address: "EP-7A, Chandragupta Marg, New Delhi 110021 India",
      city: "New Delhi",
      phone: "(+91-11) 3018059, 3012133",
      fax: "(+91-11) 3017714",
      email: "sqdelhi@del3.vsnl.net.in",
    },
  },
  {
    label: "Afghanistan",
    link: "afghanistan",
    flag: "🇦🇫",
    key: 0,
    value: "Afghanistan",
    code: "AF",
    address: {
      address: "5/50F, Shantipath, Chanakyapuri, New Delhi 110021, India",
      city: "New Delhi",
      phone: "+91-11-2410 0414",
      fax: "+91-11-2410 0412",
      email: "delhi@afghanistanembassy.org",
    },
  },
  {
    label: "Antigua & Barbuda",
    link: "antigua-and-barbuda",
    flag: "🇦🇬",
    key: 1,
    value: "Antigua & Barbuda",
    code: "AG",
    address: [],
  },
  {
    label: "Cameroon Union Republic",
    link: "cameroon-union-republic",
    flag: "🇨🇲",
    key: 2,
    value: "Cameroon Union Republic",
    code: "CM",
    address: {
      address:
        "214, Dheeraj Heritage Residency, Santacruz West, Mumbai 400054, India",
      city: "Mumbai",
      phone: "+91-22-2604 9904",
      fax: "+91-22-2604 9905",
      email: "cameroonconsulate@mtnl.net.in",
    },
  },
  {
    label: "Cape Verde",
    link: "cape-verde",
    flag: "🇨🇻",
    key: 3,
    value: "Cape Verde",
    code: "CV",
    address: [],
  },
  {
    label: "Cayman Island",
    link: "cayman-island",
    flag: "🇰🇾",
    key: 4,
    value: "Cayman Island",
    code: "KY",
    address: [],
  },
  {
    label: "Cook Islands",
    link: "cook-islands",
    flag: "🇨🇰",
    key: 5,
    value: "Cook Islands",
    code: "CK",
    address: [],
  },
  {
    label: "Cote d'Ivoire",
    link: "cote-d-ivoire",
    flag: "🇨🇮",
    key: 6,
    value: "Cote d'Ivoire",
    code: "CI",
    address: [],
  },
  {
    label: "East Timor",
    link: "east-timor",
    flag: "🇹🇱",
    key: 7,
    value: "East Timor",
    code: "TL",
    address: [],
  },
  {
    label: "Gibraltar",
    link: "gibraltar",
    flag: "🇬🇮",
    key: 8,
    value: "Gibraltar",
    code: "GI",
    address: [],
  },
  {
    label: "Guernsey",
    link: "guernsey",
    flag: "🇬🇬",
    key: 9,
    value: "Guernsey",
    code: "GG",
    address: [],
  },
  {
    label: "Isle of Man",
    link: "isle-of-man",
    flag: "🇮🇲",
    key: 10,
    value: "Isle of Man",
    code: "IM",
    address: [],
  },
  {
    label: "Jersey",
    link: "jersey",
    flag: "🇯🇪",
    key: 11,
    value: "Jersey",
    code: "JE",
    address: [],
  },
  {
    label: "Macedonia",
    link: "macedonia",
    flag: "🇲🇰",
    key: 12,
    value: "Macedonia",
    code: "MK",
    address: [],
  },
  {
    label: "Montserrat",
    link: "montserrat",
    flag: "🇲🇸",
    key: 13,
    value: "Montserrat",
    code: "MS",
    address: [],
  },
  {
    label: "Myanmar",
    link: "myanmar",
    flag: "🇲🇲",
    key: 14,
    value: "Myanmar",
    code: "MM",
    address: {
      address: "3/50 F, Nyaya Marg, Chanakyapuri, New Delhi 110021, India",
      city: "New Delhi",
      phone: "+91-11-2467 8822",
      fax: "+91-11-2467 8823",
      email: "myanmarembassydelhi@gmail.com",
    },
  },
  {
    label: "Niger Republic",
    link: "niger-republic",
    flag: "🇳🇪",
    key: 15,
    value: "Niger Republic",
    code: "NE",
    address: [],
  },
  {
    label: "Niue Island",
    link: "niue-island",
    flag: "🇳🇺",
    key: 16,
    value: "Niue Island",
    code: "NU",
    address: [],
  },
  {
    label: "Republic of Korea",
    link: "republic-of-korea",
    flag: "🇰🇷",
    key: 17,
    value: "Republic of Korea",
    code: "KR",
    address: {
      address: "9, Chandragupta Marg, Chanakyapuri, New Delhi 110021, India",
      city: "New Delhi",
      phone: "+91-11-4200 7000",
      fax: "+91-11-2688 1590",
      email: "indemb@mofa.go.kr",
    },
  },
  {
    label: "Saint Christopher and Nevis",
    link: "saint-christopher-and-nevis",
    flag: "🇰🇳",
    key: 18,
    value: "Saint Christopher and Nevis",
    code: "KN",
    address: [],
  },
  {
    label: "Saint Vincent & the Grenadines",
    link: "saint-vincent-and-the-grenadines",
    flag: "🇻🇨",
    key: 19,
    value: "Saint Vincent & the Grenadines",
    code: "VC",
    address: [],
  },
  {
    label: "Trinidad & Tobago",
    link: "trinidad-and-tobago",
    flag: "🇹🇹",
    key: 20,
    value: "Trinidad & Tobago",
    code: "TT",
    address: {
      address: "A-5, West End Colony, New Delhi 110021, India",
      city: "New Delhi",
      phone: "+91-11-2410 9344",
      fax: "+91-11-2410 9348",
      email: "hcttindia@foreign.gov.tt",
    },
  },
  {
    label: "Turks & Caicos Island",
    link: "turks-and-caicos-island",
    flag: "🇹🇨",
    key: 21,
    value: "Turks & Caicos Island",
    code: "TC",
    address: [],
  },
  {
    label: "UAE",
    link: "uae",
    flag: "🇦🇪",
    key: 22,
    value: "UAE",
    code: "AE",
    address: {
      address: "12, Chandragupta Marg, Chanakyapuri, New Delhi 110021, India",
      city: "New Delhi",
      phone: "+91-11-2611 1111",
      fax: "+91-11-2611 1991",
      email: "newdelhiemb@mofaic.gov.ae",
    },
  },
  {
    label: "USA",
    link: "usa",
    flag: "🇺🇸",
    key: 23,
    value: "USA",
    code: "US",
    address: {
      address: "Shantipath, Chanakyapuri, New Delhi 110021, India",
      city: "New Delhi",
      phone: "+91-11-2419 8000",
      fax: "+91-11-2419 0017",
      email: "consnd@state.gov",
    },
  },
  {
    label: "Vatican City-Holy See",
    link: "vatican-city-holy-see",
    flag: "🇻🇦",
    key: 24,
    value: "Vatican City-Holy See",
    code: "VA",
    address: [],
  },
  {
    label: "Zambia and Zimbabwe",
    link: "zambia-and-zimbabwe",
    flag: "🇿🇲",
    key: 25,
    value: "Zambia and Zimbabwe",
    code: "ZM-ZW",
    address: [],
  },
];

export const countriesPriceData: any = [
  {
    name: "Albania",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Andorra",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Angola",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Anguilla",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Antigua & Barbuda",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Argentina",
    eTV_30days_AprToJun: 0,
    eTV_30days_JulToMar: 0,
    eTV_1year: 0,
    eTV_5years: 0,
  },
  {
    name: "Armenia",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Aruba",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Australia",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Austria",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Azerbaijan",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Bahamas",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Barbados",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Belarus",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Belgium",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Belize",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Benin",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Bolivia",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Bosnia & Herzegovina",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Botswana",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Brazil",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Brunei",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Bulgaria",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Burundi",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Cambodia",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Cameroon Republic",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Canada",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Cape Verde",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Cayman Island",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Chile",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "China",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Colombia",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Comoros",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Costa Rica",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Cuba",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Czech Republic",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Denmark",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Djibouti",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Dominica",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Dominican Republic",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Ecuador",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "El Salvador",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Eritrea",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Estonia",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Equatorial Guinea",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Fiji",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Finland",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "France",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Gabon",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Gambia",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Georgia",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Germany",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Ghana",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Greece",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Grenada",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Guatemala",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Guinea",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Guyana",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Haiti",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Honduras",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Hungary",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Iceland",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Ireland",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Israel",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Italy",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Ivory Coast",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Jamaica",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Japan",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Jordan",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Kazakhstan",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Kenya",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Kiribati",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Kuwait",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Kyrgyzstan",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Laos",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Latvia",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Lesotho",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Liberia",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Liechtenstein",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Lithuania",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Luxembourg",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Macedonia",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Madagascar",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Malawi",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Malaysia",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Malta",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Marshall Islands",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Mauritius",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Mexico",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Micronesia",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Moldova",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Monaco",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Mongolia",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Montenegro",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Montserrat",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Mozambique",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Myanmar",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Namibia",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Nauru",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Netherlands",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "New Zealand",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Nicaragua",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Niger",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Nigeria",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Niue Island",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Norway",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Oman",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Palau",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Palestine",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Panama",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Papua New Guinea",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Paraguay",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Peru",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Philippines",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Poland",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Portugal",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Qatar",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Republic Of Korea",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Romania",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Russia",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Rwanda",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Saint Christopher And Nevis",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Saint Lucia",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Saint Vincent And The Grenadines",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Samoa",
    eTV_30days_AprToJun: 0,
    eTV_30days_JulToMar: 0,
    eTV_1year: 0,
    eTV_5years: 0,
  },
  {
    name: "San Marino",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Saudi Arabia",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Senegal",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Serbia",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Seychelles",
    eTV_30days_AprToJun: 0,
    eTV_30days_JulToMar: 0,
    eTV_1year: 0,
    eTV_5years: 0,
  },
  {
    name: "Sierra Leone",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Singapore",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 25,
    eTV_5years: 25,
  },
  {
    name: "Slovakia",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Slovenia",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Solomon Islands",
    eTV_30days_AprToJun: 0,
    eTV_30days_JulToMar: 0,
    eTV_1year: 0,
    eTV_5years: 0,
  },
  {
    name: "South Africa",
    eTV_30days_AprToJun: 0,
    eTV_30days_JulToMar: 0,
    eTV_1year: 0,
    eTV_5years: 0,
  },
  {
    name: "Spain",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Sri Lanka",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 25,
    eTV_5years: 25,
  },
  {
    name: "Suriname",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Swaziland",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Sweden",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Switzerland",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Taiwan",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Tajikistan",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Tanzania",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Thailand",
    eTV_30days_AprToJun: 0,
    eTV_30days_JulToMar: 40,
    eTV_1year: 80,
    eTV_5years: 80,
  },
  {
    name: "Togo",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Tonga",
    eTV_30days_AprToJun: 0,
    eTV_30days_JulToMar: 0,
    eTV_1year: 0,
    eTV_5years: 0,
  },
  {
    name: "Trinidad And Tobago",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Turks And Caicos",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Tuvalu",
    eTV_30days_AprToJun: 0,
    eTV_30days_JulToMar: 0,
    eTV_1year: 0,
    eTV_5years: 0,
  },
  {
    name: "Uganda",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Ukraine",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "United Arab Emirates",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "United Kingdom (UK)",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "United States Of America",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Uruguay",
    eTV_30days_AprToJun: 0,
    eTV_30days_JulToMar: 0,
    eTV_1year: 0,
    eTV_5years: 0,
  },
  {
    name: "Uzbekistan",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Vanuatu",
    eTV_30days_AprToJun: 0,
    eTV_30days_JulToMar: 0,
    eTV_1year: 0,
    eTV_5years: 0,
  },
  {
    name: "Vatican City - Holy See",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Venezuela",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Vietnam",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Zambia",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
  {
    name: "Zimbabwe",
    eTV_30days_AprToJun: 10,
    eTV_30days_JulToMar: 25,
    eTV_1year: 40,
    eTV_5years: 80,
  },
];
